---
apiVersion: v1
data:
  oned.conf: |
    LOG = [
      SYSTEM      = "file",
      DEBUG_LEVEL = 2
    ]
    MONITORING_INTERVAL_HOST      = 180
    MONITORING_INTERVAL_VM        = 180
    MONITORING_INTERVAL_DATASTORE = 300
    MONITORING_INTERVAL_MARKET    = 600
    MONITORING_THREADS  = 50
    SCRIPTS_REMOTE_DIR=/var/tmp/one
    PORT = 2633
    LISTEN_ADDRESS = "0.0.0.0"

    DB = [ BACKEND = "sqlite" ]


    VNC_PORTS = [
        START    = 5900,
        RESERVED = "43765, 10050, 9220, 8000:8100, 58358"
    ]
    FEDERATION = [
        MODE          = "STANDALONE",
        ZONE_ID       = 0,
        SERVER_ID     = -1,
        MASTER_ONED   = ""
    ]
    RAFT = [
        LIMIT_PURGE          = 100000,
        LOG_RETENTION        = 250000,
        LOG_PURGE_TIMEOUT    = 60,
        ELECTION_TIMEOUT_MS  = 5000,
        BROADCAST_TIMEOUT_MS = 500,
        XMLRPC_TIMEOUT_MS    = 1000
    ]
    DEFAULT_COST = [
        CPU_COST    = 0,
        MEMORY_COST = 0,
        DISK_COST   = 0
    ]
    NETWORK_SIZE = 254
    MAC_PREFIX   = "02:00"
    VLAN_IDS = [
        START    = "2",
        RESERVED = "0, 1, 4095"
    ]
    VXLAN_IDS = [
        START = "2"
    ]
    DATASTORE_CAPACITY_CHECK = "yes"
    DEFAULT_DEVICE_PREFIX       = "vd"
    DEFAULT_CDROM_DEVICE_PREFIX = "hd"
    DEFAULT_IMAGE_TYPE           = "OS"
    IM_MAD = [
          NAME          = "lxd",
          SUNSTONE_NAME = "LXD",
          EXECUTABLE    = "one_im_ssh",
          ARGUMENTS     = "-r 3 -t 15 -w 90 lxd" ]
    IM_MAD = [
          NAME       = "collectd",
          EXECUTABLE = "collectd",
          ARGUMENTS  = "-p 32124 -f 5 -t 50 -i 60" ]
    IM_MAD = [
          NAME          = "kvm",
          SUNSTONE_NAME = "KVM",
          EXECUTABLE    = "one_im_ssh",
          ARGUMENTS     = "-r 3 -t 15 -w 90 kvm" ]
    IM_MAD = [
          NAME          = "vcenter",
          SUNSTONE_NAME = "VMWare vCenter",
          EXECUTABLE    = "one_im_sh",
          ARGUMENTS     = "-c -t 15 -r 0 vcenter" ]
    VM_MAD = [
        NAME           = "lxd",
        SUNSTONE_NAME  = "LXD",
        EXECUTABLE     = "one_vmm_exec",
        ARGUMENTS      = "-t 15 -r 0 lxd",
        # DEFAULT        = "vmm_exec/vmm_exec_lxd.conf",
        TYPE           = "xml",
        KEEP_SNAPSHOTS = "no",
        IMPORTED_VMS_ACTIONS = "terminate, terminate-hard, reboot, reboot-hard, poweroff, poweroff-hard, suspend, resume, stop, delete,  nic-attach, nic-detach"
    ]
    VM_MAD = [
        NAME           = "kvm",
        SUNSTONE_NAME  = "KVM",
        EXECUTABLE     = "one_vmm_exec",
        ARGUMENTS      = "-t 15 -r 0 kvm",
        DEFAULT        = "vmm_exec/vmm_exec_kvm.conf",
        TYPE           = "kvm",
        KEEP_SNAPSHOTS = "yes",
        IMPORTED_VMS_ACTIONS = "terminate, terminate-hard, hold, release, suspend,
            resume, delete, reboot, reboot-hard, resched, unresched, disk-attach,
            disk-detach, nic-attach, nic-detach, snapshot-create, snapshot-delete"
    ]
    VM_MAD = [
        NAME              = "vcenter",
        SUNSTONE_NAME     = "VMWare vCenter",
        EXECUTABLE        = "one_vmm_sh",
        ARGUMENTS         = "-p -t 15 -r 0 vcenter -s sh",
        DEFAULT           = "vmm_exec/vmm_exec_vcenter.conf",
        TYPE              = "xml",
        KEEP_SNAPSHOTS    = "yes",
        DS_LIVE_MIGRATION = "yes",
        IMPORTED_VMS_ACTIONS = "terminate, terminate-hard, hold, release, suspend,
            resume, delete, reboot, reboot-hard, resched, unresched, poweroff,
            poweroff-hard, disk-attach, disk-detach, nic-attach, nic-detach,
            snapshot-create, snapshot-delete, migrate, live-migrate"
    ]
    TM_MAD = [
        EXECUTABLE = "one_tm",
        ARGUMENTS = "-t 15 -d dummy,lvm,shared,fs_lvm,qcow2,ssh,ceph,dev,vcenter,iscsi_libvirt"
    ]
    DATASTORE_MAD = [
        EXECUTABLE = "one_datastore",
        ARGUMENTS  = "-t 15 -d dummy,fs,lvm,ceph,dev,iscsi_libvirt,vcenter -s shared,ssh,ceph,fs_lvm,qcow2,vcenter"
    ]
    MARKET_MAD = [
        EXECUTABLE = "one_market",
        ARGUMENTS  = "-t 15 -m http,s3,one,linuxcontainers"
    ]
    IPAM_MAD = [
        EXECUTABLE = "one_ipam",
        ARGUMENTS  = "-t 1 -i dummy"
    ]
    HM_MAD = [
        EXECUTABLE = "one_hm" ]



    AUTH_MAD = [
        EXECUTABLE = "one_auth_mad",
        AUTHN = "ssh,x509,ldap,server_cipher,server_x509"
    ]
    DEFAULT_AUTH = "ldap"
    SESSION_EXPIRATION_TIME = 900
    ENABLE_OTHER_PERMISSIONS = "YES"
    DEFAULT_UMASK = 177
    ONEGATE_ENDPOINT = "https://gate.opennebula.example.org"
    VM_ADMIN_OPERATIONS  = "migrate, delete, recover, retry, deploy, resched"
    VM_MANAGE_OPERATIONS = "undeploy, hold, release, stop, suspend, resume, reboot,
        poweroff, disk-attach, nic-attach, disk-snapshot, terminate, disk-resize,
        snapshot, updateconf, rename, resize, update, disk-saveas"
    VM_USE_OPERATIONS    = ""
    DEFAULT_VDC_HOST_ACL      = ""
    DEFAULT_VDC_VNET_ACL      = ""
    DEFAULT_VDC_DATASTORE_ACL = ""
    DEFAULT_VDC_CLUSTER_HOST_ACL      = ""
    DEFAULT_VDC_CLUSTER_NET_ACL       = ""
    DEFAULT_VDC_CLUSTER_DATASTORE_ACL = ""
    VM_RESTRICTED_ATTR = "CONTEXT/FILES"
    VM_RESTRICTED_ATTR = "NIC/MAC"
    VM_RESTRICTED_ATTR = "NIC/VLAN_ID"
    VM_RESTRICTED_ATTR = "NIC/BRIDGE"
    VM_RESTRICTED_ATTR = "NIC/INBOUND_AVG_BW"
    VM_RESTRICTED_ATTR = "NIC/INBOUND_PEAK_BW"
    VM_RESTRICTED_ATTR = "NIC/INBOUND_PEAK_KB"
    VM_RESTRICTED_ATTR = "NIC/OUTBOUND_AVG_BW"
    VM_RESTRICTED_ATTR = "NIC/OUTBOUND_PEAK_BW"
    VM_RESTRICTED_ATTR = "NIC/OUTBOUND_PEAK_KB"
    VM_RESTRICTED_ATTR = "NIC/OPENNEBULA_MANAGED"
    VM_RESTRICTED_ATTR = "NIC/VCENTER_INSTANCE_ID"
    VM_RESTRICTED_ATTR = "NIC/VCENTER_NET_REF"
    VM_RESTRICTED_ATTR = "NIC/VCENTER_PORTGROUP_TYPE"
    VM_RESTRICTED_ATTR = "NIC/EXTERNAL"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/MAC"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/VLAN_ID"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/BRIDGE"
    VM_RESTRICTED_ATTR = "NIC_DEFAULT/EXTERNAL"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/INBOUND_AVG_BW"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/INBOUND_PEAK_BW"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/INBOUND_PEAK_KB"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/OUTBOUND_AVG_BW"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/OUTBOUND_PEAK_BW"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/OUTBOUND_PEAK_KB"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/OPENNEBULA_MANAGED"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/VCENTER_INSTANCE_ID"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/VCENTER_NET_REF"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/VCENTER_PORTGROUP_TYPE"
    VM_RESTRICTED_ATTR = "NIC_ALIAS/EXTERNAL"
    VM_RESTRICTED_ATTR = "NIC_DEFAULT/MAC"
    VM_RESTRICTED_ATTR = "NIC_DEFAULT/VLAN_ID"
    VM_RESTRICTED_ATTR = "NIC_DEFAULT/BRIDGE"
    VM_RESTRICTED_ATTR = "DISK/TOTAL_BYTES_SEC"
    VM_RESTRICTED_ATTR = "DISK/TOTAL_BYTES_SEC_MAX_LENGTH"
    VM_RESTRICTED_ATTR = "DISK/TOTAL_BYTES_SEC_MAX"
    VM_RESTRICTED_ATTR = "DISK/READ_BYTES_SEC"
    VM_RESTRICTED_ATTR = "DISK/READ_BYTES_SEC_MAX_LENGTH"
    VM_RESTRICTED_ATTR = "DISK/READ_BYTES_SEC_MAX"
    VM_RESTRICTED_ATTR = "DISK/WRITE_BYTES_SEC"
    VM_RESTRICTED_ATTR = "DISK/WRITE_BYTES_SEC_MAX_LENGTH"
    VM_RESTRICTED_ATTR = "DISK/WRITE_BYTES_SEC_MAX"
    VM_RESTRICTED_ATTR = "DISK/TOTAL_IOPS_SEC"
    VM_RESTRICTED_ATTR = "DISK/TOTAL_IOPS_SEC_MAX_LENGTH"
    VM_RESTRICTED_ATTR = "DISK/TOTAL_IOPS_SEC_MAX"
    VM_RESTRICTED_ATTR = "DISK/READ_IOPS_SEC"
    VM_RESTRICTED_ATTR = "DISK/READ_IOPS_SEC_MAX_LENGTH"
    VM_RESTRICTED_ATTR = "DISK/READ_IOPS_SEC_MAX"
    VM_RESTRICTED_ATTR = "DISK/WRITE_IOPS_SEC"
    VM_RESTRICTED_ATTR = "DISK/WRITE_IOPS_SEC_MAX_LENGTH"
    VM_RESTRICTED_ATTR = "DISK/WRITE_IOPS_SEC_MAX"
    VM_RESTRICTED_ATTR = "DISK/OPENNEBULA_MANAGED"
    VM_RESTRICTED_ATTR = "DISK/VCENTER_DS_REF"
    VM_RESTRICTED_ATTR = "DISK/VCENTER_INSTANCE_ID"
    VM_RESTRICTED_ATTR = "DISK/ORIGINAL_SIZE"
    VM_RESTRICTED_ATTR = "DISK/SIZE_PREV"
    VM_RESTRICTED_ATTR = "CPU_COST"
    VM_RESTRICTED_ATTR = "MEMORY_COST"
    VM_RESTRICTED_ATTR = "DISK_COST"
    VM_RESTRICTED_ATTR = "PCI"
    VM_RESTRICTED_ATTR = "EMULATOR"
    VM_RESTRICTED_ATTR = "RAW"
    VM_RESTRICTED_ATTR = "USER_PRIORITY"
    VM_RESTRICTED_ATTR = "USER_INPUTS/CPU"
    VM_RESTRICTED_ATTR = "USER_INPUTS/MEMORY"
    VM_RESTRICTED_ATTR = "USER_INPUTS/VCPU"
    VM_RESTRICTED_ATTR = "VCENTER_VM_FOLDER"
    VM_RESTRICTED_ATTR = "VCENTER_ESX_HOST"
    VM_RESTRICTED_ATTR = "VPS_VM"
    VM_RESTRICTED_ATTR = "DEDICATED_CPU"
    VM_RESTRICTED_ATTR = "VPS_TASK_HNEDKA_NOTIFY"
    VM_RESTRICTED_ATTR = "VPS_TASK_REBOOT_VM"
    VM_RESTRICTED_ATTR = "VPS_TASK_REMOVE_CONTEXT_FIELDS"
    VM_RESTRICTED_ATTR = "VPS_TASK_REMOVE_FIELDS"
    VM_RESTRICTED_ATTR = "VPS_TASK_REMOVE_GROUP"
    VM_RESTRICTED_ATTR = "VPS_TASK_REMOVE_NETWORK"
    VM_RESTRICTED_ATTR = "VPS_TASK_REMOVE_PASSWORD"
    VM_RESTRICTED_ATTR = "VPS_TASK_REMOVE_USER"
    VM_RESTRICTED_ATTR = "VPS_TASK_REMOVE_EXPIRED_ISOS"
    VM_RESTRICTED_ATTR = "VPS_TASK_RESUME_VM"
    VM_RESTRICTED_ATTR = "VPS_TASK_SHUTDOWN_VM"
    VM_RESTRICTED_ATTR = "ONE_MIGRATE_FROM"
    VM_RESTRICTED_ATTR = "ONE_MIGRATE_STATE"
    VM_RESTRICTED_ATTR = "RAW/DATA"
    VM_RESTRICTED_ATTR = "RAW/TYPE"
    VM_RESTRICTED_ATTR = "GRAPHICS"
    VM_RESTRICTED_ATTR = "DISK/ALLOW_ORPHANS"
    VM_RESTRICTED_ATTR = "DISK/CACHE"
    VM_RESTRICTED_ATTR = "DISK/DISCARD"
    VM_RESTRICTED_ATTR = "DISK/DRIVER"
    VM_RESTRICTED_ATTR = "DISK/IO"
    VM_RESTRICTED_ATTR = "DISK/VCENTER_ADAPTER_TYPE"
    VM_RESTRICTED_ATTR = "DISK/VCENTER_DISK_TYPE"
    VM_RESTRICTED_ATTR = "LABELS"
    VM_RESTRICTED_ATTR = "LOGO"
    IMAGE_RESTRICTED_ATTR = "LABELS"
    IMAGE_RESTRICTED_ATTR = "DEV_PREFIX"
    IMAGE_RESTRICTED_ATTR = "DRIVER"
    IMAGE_RESTRICTED_ATTR = "TARGET"
    IMAGE_RESTRICTED_ATTR = "PERSISTENT"
    IMAGE_RESTRICTED_ATTR = "SOURCE"
    IMAGE_RESTRICTED_ATTR = "VCENTER_IMPORTED"
    VNET_RESTRICTED_ATTR = "VN_MAD"
    VNET_RESTRICTED_ATTR = "PHYDEV"
    VNET_RESTRICTED_ATTR = "VLAN_ID"
    VNET_RESTRICTED_ATTR = "BRIDGE"
    VNET_RESTRICTED_ATTR = "CONF"
    VNET_RESTRICTED_ATTR = "BRIDGE_CONF"
    VNET_RESTRICTED_ATTR = "OVS_BRIDGE_CONF"
    VNET_RESTRICTED_ATTR = "IP_LINK_CONF"
    VNET_RESTRICTED_ATTR = "FILTER_IP_SPOOFING"
    VNET_RESTRICTED_ATTR = "FILTER_MAC_SPOOFING"
    VNET_RESTRICTED_ATTR = "AR/VN_MAD"
    VNET_RESTRICTED_ATTR = "AR/PHYDEV"
    VNET_RESTRICTED_ATTR = "AR/VLAN_ID"
    VNET_RESTRICTED_ATTR = "AR/BRIDGE"
    VNET_RESTRICTED_ATTR = "AR/FILTER_IP_SPOOFING"
    VNET_RESTRICTED_ATTR = "AR/FILTER_MAC_SPOOFING"
    VNET_RESTRICTED_ATTR = "CLUSTER_IDS"
    VNET_RESTRICTED_ATTR = "EXTERNAL"
    INHERIT_DATASTORE_ATTR  = "CEPH_HOST"
    INHERIT_DATASTORE_ATTR  = "CEPH_SECRET"
    INHERIT_DATASTORE_ATTR  = "CEPH_KEY"
    INHERIT_DATASTORE_ATTR  = "CEPH_USER"
    INHERIT_DATASTORE_ATTR  = "CEPH_CONF"
    INHERIT_DATASTORE_ATTR  = "POOL_NAME"
    INHERIT_DATASTORE_ATTR  = "ISCSI_USER"
    INHERIT_DATASTORE_ATTR  = "ISCSI_USAGE"
    INHERIT_DATASTORE_ATTR  = "ISCSI_HOST"
    INHERIT_IMAGE_ATTR      = "ISCSI_USER"
    INHERIT_IMAGE_ATTR      = "ISCSI_USAGE"
    INHERIT_IMAGE_ATTR      = "ISCSI_HOST"
    INHERIT_IMAGE_ATTR      = "ISCSI_IQN"
    INHERIT_DATASTORE_ATTR  = "GLUSTER_HOST"
    INHERIT_DATASTORE_ATTR  = "GLUSTER_VOLUME"
    INHERIT_DATASTORE_ATTR  = "DISK_TYPE"
    INHERIT_DATASTORE_ATTR  = "ALLOW_ORPHANS"
    INHERIT_DATASTORE_ATTR  = "VCENTER_ADAPTER_TYPE"
    INHERIT_DATASTORE_ATTR  = "VCENTER_DISK_TYPE"
    INHERIT_DATASTORE_ATTR  = "VCENTER_DS_REF"
    INHERIT_DATASTORE_ATTR  = "VCENTER_DS_IMAGE_DIR"
    INHERIT_DATASTORE_ATTR  = "VCENTER_DS_VOLATILE_DIR"
    INHERIT_DATASTORE_ATTR  = "VCENTER_INSTANCE_ID"
    INHERIT_IMAGE_ATTR      = "DISK_TYPE"
    INHERIT_IMAGE_ATTR      = "VCENTER_ADAPTER_TYPE"
    INHERIT_IMAGE_ATTR      = "VCENTER_DISK_TYPE"
    INHERIT_VNET_ATTR       = "VLAN_TAGGED_ID"
    INHERIT_VNET_ATTR       = "FILTER_IP_SPOOFING"
    INHERIT_VNET_ATTR       = "FILTER_MAC_SPOOFING"
    INHERIT_VNET_ATTR       = "MTU"
    INHERIT_VNET_ATTR       = "INBOUND_AVG_BW"
    INHERIT_VNET_ATTR       = "INBOUND_PEAK_BW"
    INHERIT_VNET_ATTR       = "INBOUND_PEAK_KB"
    INHERIT_VNET_ATTR       = "OUTBOUND_AVG_BW"
    INHERIT_VNET_ATTR       = "OUTBOUND_PEAK_BW"
    INHERIT_VNET_ATTR       = "OUTBOUND_PEAK_KB"
    INHERIT_VNET_ATTR       = "CONF"
    INHERIT_VNET_ATTR       = "BRIDGE_CONF"
    INHERIT_VNET_ATTR       = "OVS_BRIDGE_CONF"
    INHERIT_VNET_ATTR       = "IP_LINK_CONF"
    INHERIT_VNET_ATTR       = "EXTERNAL"
    INHERIT_VNET_ATTR       = "VCENTER_NET_REF"
    INHERIT_VNET_ATTR       = "VCENTER_SWITCH_NAME"
    INHERIT_VNET_ATTR       = "VCENTER_SWITCH_NPORTS"
    INHERIT_VNET_ATTR       = "VCENTER_PORTGROUP_TYPE"
    INHERIT_VNET_ATTR       = "VCENTER_CCR_REF"
    INHERIT_VNET_ATTR       = "VCENTER_INSTANCE_ID"
    TM_MAD_CONF = [
        NAME = "dummy", LN_TARGET = "NONE", CLONE_TARGET = "SYSTEM", SHARED = "YES",
        DS_MIGRATE = "YES"
    ]
    TM_MAD_CONF = [
        NAME = "lvm", LN_TARGET = "NONE", CLONE_TARGET = "SELF", SHARED = "YES"
    ]
    TM_MAD_CONF = [
        NAME = "shared", LN_TARGET = "NONE", CLONE_TARGET = "SYSTEM", SHARED = "YES",
        DS_MIGRATE = "YES", TM_MAD_SYSTEM = "ssh", LN_TARGET_SSH = "SYSTEM",
        CLONE_TARGET_SSH = "SYSTEM", DISK_TYPE_SSH = "FILE"
    ]
    TM_MAD_CONF = [
        NAME = "fs_lvm", LN_TARGET = "SYSTEM", CLONE_TARGET = "SYSTEM", SHARED="YES",
        DRIVER = "raw"
    ]
    TM_MAD_CONF = [
        NAME = "qcow2", LN_TARGET = "NONE", CLONE_TARGET = "SYSTEM", SHARED = "YES",
        DS_MIGRATE = "YES", TM_MAD_SYSTEM = "ssh", LN_TARGET_SSH = "SYSTEM",
        CLONE_TARGET_SSH = "SYSTEM", DISK_TYPE_SSH = "FILE", DRIVER = "qcow2"
    ]
    TM_MAD_CONF = [
        NAME = "ssh", LN_TARGET = "SYSTEM", CLONE_TARGET = "SYSTEM", SHARED = "NO",
        DS_MIGRATE = "YES"
    ]
    TM_MAD_CONF = [
        NAME = "ceph", LN_TARGET = "NONE", CLONE_TARGET = "SELF", SHARED = "YES",
        DS_MIGRATE = "NO", DRIVER = "raw", ALLOW_ORPHANS="mixed",
        TM_MAD_SYSTEM = "ssh,shared", LN_TARGET_SSH = "SYSTEM", CLONE_TARGET_SSH = "SYSTEM",
        DISK_TYPE_SSH = "FILE", TM_MAD_SYSTEM = "shared", LN_TARGET_SHARED = "NONE",
        CLONE_TARGET_SHARED = "SELF", DISK_TYPE_SHARED = "RBD"
    ]
    TM_MAD_CONF = [
        NAME = "iscsi_libvirt", LN_TARGET = "NONE", CLONE_TARGET = "SELF", SHARED = "YES",
        DS_MIGRATE = "NO"
    ]
    TM_MAD_CONF = [
        NAME = "dev", LN_TARGET = "NONE", CLONE_TARGET = "NONE", SHARED = "YES"
    ]
    TM_MAD_CONF = [
        NAME = "vcenter", LN_TARGET = "NONE", CLONE_TARGET = "SYSTEM", SHARED = "YES"
    ]
    DS_MAD_CONF = [
        NAME = "ceph",
        REQUIRED_ATTRS = "DISK_TYPE,BRIDGE_LIST",
        PERSISTENT_ONLY = "NO",
        MARKETPLACE_ACTIONS = "export"
    ]
    DS_MAD_CONF = [
        NAME = "dev", REQUIRED_ATTRS = "DISK_TYPE", PERSISTENT_ONLY = "YES"
    ]
    DS_MAD_CONF = [
        NAME = "iscsi_libvirt", REQUIRED_ATTRS = "DISK_TYPE,ISCSI_HOST",
        PERSISTENT_ONLY = "YES"
    ]
    DS_MAD_CONF = [
        NAME = "dummy", REQUIRED_ATTRS = "", PERSISTENT_ONLY = "NO"
    ]
    DS_MAD_CONF = [
        NAME = "fs", REQUIRED_ATTRS = "", PERSISTENT_ONLY = "NO",
        MARKETPLACE_ACTIONS = "export"
    ]
    DS_MAD_CONF = [
        NAME = "lvm", REQUIRED_ATTRS = "DISK_TYPE,BRIDGE_LIST",
        PERSISTENT_ONLY = "NO"
    ]
    DS_MAD_CONF = [
        NAME = "vcenter",
        REQUIRED_ATTRS = "VCENTER_INSTANCE_ID,VCENTER_DS_REF,VCENTER_DC_REF",
        PERSISTENT_ONLY = "NO",
        MARKETPLACE_ACTIONS = "export"
    ]
    MARKET_MAD_CONF = [
        NAME = "one",
        SUNSTONE_NAME  = "OpenNebula.org Marketplace",
        REQUIRED_ATTRS = "",
        APP_ACTIONS = "monitor",
        PUBLIC = "yes"
    ]
    MARKET_MAD_CONF = [
        NAME = "http",
        SUNSTONE_NAME  = "HTTP server",
        REQUIRED_ATTRS = "BASE_URL,PUBLIC_DIR",
        APP_ACTIONS = "create, delete, monitor"
    ]
    MARKET_MAD_CONF = [
        NAME = "s3",
        SUNSTONE_NAME = "Amazon S3",
        REQUIRED_ATTRS = "ACCESS_KEY_ID,SECRET_ACCESS_KEY,REGION,BUCKET",
        APP_ACTIONS = "create, delete, monitor"
    ]
    MARKET_MAD_CONF = [
        NAME = "linuxcontainers",
        SUNSTONE_NAME = "LinuxContainers.org",
        REQUIRED_ATTRS = "",
        APP_ACTIONS = "monitor",
        PUBLIC = "yes"
    ]
    AUTH_MAD_CONF = [
        NAME = "core",
        PASSWORD_CHANGE = "YES",
        DRIVER_MANAGED_GROUPS = "NO",
        MAX_TOKEN_TIME = "-1"
    ]
    AUTH_MAD_CONF = [
        NAME = "public",
        PASSWORD_CHANGE = "NO",
        DRIVER_MANAGED_GROUPS = "NO",
        MAX_TOKEN_TIME = "-1"
    ]
    AUTH_MAD_CONF = [
        NAME = "ssh",
        PASSWORD_CHANGE = "YES",
        DRIVER_MANAGED_GROUPS = "NO",
        MAX_TOKEN_TIME = "-1"
    ]
    AUTH_MAD_CONF = [
        NAME = "x509",
        PASSWORD_CHANGE = "NO",
        DRIVER_MANAGED_GROUPS = "NO",
        MAX_TOKEN_TIME = "-1"
    ]
    AUTH_MAD_CONF = [
        NAME = "ldap",
        PASSWORD_CHANGE = "YES",
        DRIVER_MANAGED_GROUPS = "YES",
        MAX_TOKEN_TIME = "86400"
    ]
    AUTH_MAD_CONF = [
        NAME = "server_cipher",
        PASSWORD_CHANGE = "NO",
        DRIVER_MANAGED_GROUPS = "NO",
        MAX_TOKEN_TIME = "-1"
    ]
    AUTH_MAD_CONF = [
        NAME = "server_x509",
        PASSWORD_CHANGE = "NO",
        DRIVER_MANAGED_GROUPS = "NO",
        MAX_TOKEN_TIME = "-1"
    ]
    VN_MAD_CONF = [
        NAME = "dummy",
        BRIDGE_TYPE = "linux"
    ]
    VN_MAD_CONF = [
        NAME = "802.1Q",
        BRIDGE_TYPE = "linux"
    ]
    VN_MAD_CONF = [
        NAME = "ebtables",
        BRIDGE_TYPE = "linux"
    ]
    VN_MAD_CONF = [
        NAME = "fw",
        BRIDGE_TYPE = "linux"
    ]
    VN_MAD_CONF = [
        NAME = "ovswitch",
        BRIDGE_TYPE = "openvswitch"
    ]
    VN_MAD_CONF = [
        NAME = "vxlan",
        BRIDGE_TYPE = "linux"
    ]
    VN_MAD_CONF = [
        NAME = "vcenter",
        BRIDGE_TYPE = "vcenter_port_groups"
    ]
    VN_MAD_CONF = [
        NAME = "ovswitch_vxlan",
        BRIDGE_TYPE = "openvswitch"
    ]
    VN_MAD_CONF = [
        NAME = "bridge",
        BRIDGE_TYPE = "linux"
    ]
kind: ConfigMap
metadata:
  labels:
    ksonnet.io/component: oned-config
  name: opennebula-oned
